### ISSUE TITLE
Performance comparison with Linux XDP

### ISSUE THREAD

**Issue by ramenhost** [lucypa/sDDF#1]
Slide 17 from the seL4 2022 summit [here](https://trustworthy.systems/publications/papers/Parker_22%3Asel4s.slides.pdf) shows performance comparison against the Linux network stack.  
[suggestion] It would be great to have a similar comparison against Linux's eBPF based eXpress Data Path (XDP). XDP based user-space stack seems to be more comparable to sDDF by design than the Linux kernel stack.

**Comment by Indanz** [comment]
I think one reason why the Linux performance is so bad is because Linux's fec drivers maps the DMA buffers uncached, while Lucy maps it cacheable and does manual cache maintenance. If XDP is still using the same fec driver, it still won't be a fair comparison, because it will still be using the crappy imx fec driver.

**Comment by ramenhost** [comment]
The kernel to user-space memory copy might incur more overhead than cache misses, whereas XDP provides zero-copy data path. That's why wanted to see the performance comparision.
